package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApplicationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationAllPropertiesEquals(Application expected, Application actual) {
        assertApplicationAutoGeneratedPropertiesEquals(expected, actual);
        assertApplicationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationAllUpdatablePropertiesEquals(Application expected, Application actual) {
        assertApplicationUpdatableFieldsEquals(expected, actual);
        assertApplicationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationAutoGeneratedPropertiesEquals(Application expected, Application actual) {
        assertThat(actual)
            .as("Verify Application auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationUpdatableFieldsEquals(Application expected, Application actual) {
        assertThat(actual)
            .as("Verify Application relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDateAjout()).as("check dateAjout").isEqualTo(expected.getDateAjout()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApplicationUpdatableRelationshipsEquals(Application expected, Application actual) {
        // empty method
    }
}
