package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CommunauteNanditeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunauteNanditeAllPropertiesEquals(CommunauteNandite expected, CommunauteNandite actual) {
        assertCommunauteNanditeAutoGeneratedPropertiesEquals(expected, actual);
        assertCommunauteNanditeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunauteNanditeAllUpdatablePropertiesEquals(CommunauteNandite expected, CommunauteNandite actual) {
        assertCommunauteNanditeUpdatableFieldsEquals(expected, actual);
        assertCommunauteNanditeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunauteNanditeAutoGeneratedPropertiesEquals(CommunauteNandite expected, CommunauteNandite actual) {
        assertThat(actual)
            .as("Verify CommunauteNandite auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunauteNanditeUpdatableFieldsEquals(CommunauteNandite expected, CommunauteNandite actual) {
        assertThat(actual)
            .as("Verify CommunauteNandite relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCommunauteNanditeUpdatableRelationshipsEquals(CommunauteNandite expected, CommunauteNandite actual) {
        assertThat(actual)
            .as("Verify CommunauteNandite relationships")
            .satisfies(a -> assertThat(a.getMembreses()).as("check membreses").isEqualTo(expected.getMembreses()));
    }
}
