package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContenuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuAllPropertiesEquals(Contenu expected, Contenu actual) {
        assertContenuAutoGeneratedPropertiesEquals(expected, actual);
        assertContenuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuAllUpdatablePropertiesEquals(Contenu expected, Contenu actual) {
        assertContenuUpdatableFieldsEquals(expected, actual);
        assertContenuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuAutoGeneratedPropertiesEquals(Contenu expected, Contenu actual) {
        assertThat(actual)
            .as("Verify Contenu auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuUpdatableFieldsEquals(Contenu expected, Contenu actual) {
        assertThat(actual)
            .as("Verify Contenu relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTypeContenu()).as("check typeContenu").isEqualTo(expected.getTypeContenu()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getDatePublication()).as("check datePublication").isEqualTo(expected.getDatePublication()))
            .satisfies(a -> assertThat(a.getDerniereMiseAJour()).as("check derniereMiseAJour").isEqualTo(expected.getDerniereMiseAJour()))
            .satisfies(a -> assertThat(a.getProchaineRevue()).as("check prochaineRevue").isEqualTo(expected.getProchaineRevue()))
            .satisfies(a -> assertThat(a.getMotsCles()).as("check motsCles").isEqualTo(expected.getMotsCles()))
            .satisfies(a -> assertThat(a.getTranscription()).as("check transcription").isEqualTo(expected.getTranscription()))
            .satisfies(a -> assertThat(a.getProgression()).as("check progression").isEqualTo(expected.getProgression()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContenuUpdatableRelationshipsEquals(Contenu expected, Contenu actual) {
        assertThat(actual)
            .as("Verify Contenu relationships")
            .satisfies(a -> assertThat(a.getApplication()).as("check application").isEqualTo(expected.getApplication()))
            .satisfies(a -> assertThat(a.getModule()).as("check module").isEqualTo(expected.getModule()))
            .satisfies(a -> assertThat(a.getMetier()).as("check metier").isEqualTo(expected.getMetier()))
            .satisfies(a -> assertThat(a.getAuteur()).as("check auteur").isEqualTo(expected.getAuteur()))
            .satisfies(a -> assertThat(a.getValidateur()).as("check validateur").isEqualTo(expected.getValidateur()));
    }
}
