package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiscussionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscussionAllPropertiesEquals(Discussion expected, Discussion actual) {
        assertDiscussionAutoGeneratedPropertiesEquals(expected, actual);
        assertDiscussionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscussionAllUpdatablePropertiesEquals(Discussion expected, Discussion actual) {
        assertDiscussionUpdatableFieldsEquals(expected, actual);
        assertDiscussionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscussionAutoGeneratedPropertiesEquals(Discussion expected, Discussion actual) {
        assertThat(actual)
            .as("Verify Discussion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscussionUpdatableFieldsEquals(Discussion expected, Discussion actual) {
        assertThat(actual)
            .as("Verify Discussion relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiscussionUpdatableRelationshipsEquals(Discussion expected, Discussion actual) {
        assertThat(actual)
            .as("Verify Discussion relationships")
            .satisfies(a -> assertThat(a.getCreateur()).as("check createur").isEqualTo(expected.getCreateur()))
            .satisfies(a -> assertThat(a.getCommunauteNandite()).as("check communauteNandite").isEqualTo(expected.getCommunauteNandite()));
    }
}
