package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FAQAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFAQAllPropertiesEquals(FAQ expected, FAQ actual) {
        assertFAQAutoGeneratedPropertiesEquals(expected, actual);
        assertFAQAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFAQAllUpdatablePropertiesEquals(FAQ expected, FAQ actual) {
        assertFAQUpdatableFieldsEquals(expected, actual);
        assertFAQUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFAQAutoGeneratedPropertiesEquals(FAQ expected, FAQ actual) {
        assertThat(actual)
            .as("Verify FAQ auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFAQUpdatableFieldsEquals(FAQ expected, FAQ actual) {
        assertThat(actual)
            .as("Verify FAQ relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getReponse()).as("check reponse").isEqualTo(expected.getReponse()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFAQUpdatableRelationshipsEquals(FAQ expected, FAQ actual) {
        assertThat(actual)
            .as("Verify FAQ relationships")
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()));
    }
}
