package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeedBackAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackAllPropertiesEquals(FeedBack expected, FeedBack actual) {
        assertFeedBackAutoGeneratedPropertiesEquals(expected, actual);
        assertFeedBackAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackAllUpdatablePropertiesEquals(FeedBack expected, FeedBack actual) {
        assertFeedBackUpdatableFieldsEquals(expected, actual);
        assertFeedBackUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackAutoGeneratedPropertiesEquals(FeedBack expected, FeedBack actual) {
        assertThat(actual)
            .as("Verify FeedBack auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackUpdatableFieldsEquals(FeedBack expected, FeedBack actual) {
        assertThat(actual)
            .as("Verify FeedBack relevant properties")
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getStatutTraitement()).as("check statutTraitement").isEqualTo(expected.getStatutTraitement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackUpdatableRelationshipsEquals(FeedBack expected, FeedBack actual) {
        assertThat(actual)
            .as("Verify FeedBack relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()))
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()));
    }
}
