package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetierAllPropertiesEquals(Metier expected, Metier actual) {
        assertMetierAutoGeneratedPropertiesEquals(expected, actual);
        assertMetierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetierAllUpdatablePropertiesEquals(Metier expected, Metier actual) {
        assertMetierUpdatableFieldsEquals(expected, actual);
        assertMetierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetierAutoGeneratedPropertiesEquals(Metier expected, Metier actual) {
        assertThat(actual)
            .as("Verify Metier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetierUpdatableFieldsEquals(Metier expected, Metier actual) {
        assertThat(actual)
            .as("Verify Metier relevant properties")
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetierUpdatableRelationshipsEquals(Metier expected, Metier actual) {
        // empty method
    }
}
