package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SignalementMessageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignalementMessageAllPropertiesEquals(SignalementMessage expected, SignalementMessage actual) {
        assertSignalementMessageAutoGeneratedPropertiesEquals(expected, actual);
        assertSignalementMessageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignalementMessageAllUpdatablePropertiesEquals(SignalementMessage expected, SignalementMessage actual) {
        assertSignalementMessageUpdatableFieldsEquals(expected, actual);
        assertSignalementMessageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignalementMessageAutoGeneratedPropertiesEquals(SignalementMessage expected, SignalementMessage actual) {
        assertThat(actual)
            .as("Verify SignalementMessage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignalementMessageUpdatableFieldsEquals(SignalementMessage expected, SignalementMessage actual) {
        assertThat(actual)
            .as("Verify SignalementMessage relevant properties")
            .satisfies(a -> assertThat(a.getMotif()).as("check motif").isEqualTo(expected.getMotif()))
            .satisfies(a -> assertThat(a.getDateSignalement()).as("check dateSignalement").isEqualTo(expected.getDateSignalement()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignalementMessageUpdatableRelationshipsEquals(SignalementMessage expected, SignalementMessage actual) {
        assertThat(actual)
            .as("Verify SignalementMessage relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()));
    }
}
