package sn.dove.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UtilisateurRoleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisateurRoleAllPropertiesEquals(UtilisateurRole expected, UtilisateurRole actual) {
        assertUtilisateurRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertUtilisateurRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisateurRoleAllUpdatablePropertiesEquals(UtilisateurRole expected, UtilisateurRole actual) {
        assertUtilisateurRoleUpdatableFieldsEquals(expected, actual);
        assertUtilisateurRoleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisateurRoleAutoGeneratedPropertiesEquals(UtilisateurRole expected, UtilisateurRole actual) {
        assertThat(actual)
            .as("Verify UtilisateurRole auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisateurRoleUpdatableFieldsEquals(UtilisateurRole expected, UtilisateurRole actual) {
        // empty method
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUtilisateurRoleUpdatableRelationshipsEquals(UtilisateurRole expected, UtilisateurRole actual) {
        assertThat(actual)
            .as("Verify UtilisateurRole relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()));
    }
}
